# User settings
username: Phill Fernandes
user_description: Developer at Stormlight Tech
user_title:  PHP/JS Developer
email: Phill@CreativeTech.me
twitter_username: TheRealWymoree
github_username:  PhillF
gplus_username:
